"""add comprehension questions and quiz attempts

Revision ID: 3fd92743c323
Revises: ce57d8fa83f6
Create Date: 2026-09-25 20:01:16.505529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fd92743c323'
down_revision: Union[str, Sequence[str], None] = 'ce57d8fa83f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Additive (a new table and a nullable column), so older code runs on
    this schema after a rollback; it just ignores both and shows no quiz.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_attempts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('story_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('correct_count >= 0 AND correct_count <= question_count', name='quiz_attempts_correct_count_check'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('quiz_attempts_story_id_idx', 'quiz_attempts', ['story_id'], unique=False)
    op.create_index('quiz_attempts_user_id_idx', 'quiz_attempts', ['user_id'], unique=False)
    op.add_column('stories', sa.Column('comprehension_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'comprehension_questions')
    op.drop_index('quiz_attempts_user_id_idx', table_name='quiz_attempts')
    op.drop_index('quiz_attempts_story_id_idx', table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    # ### end Alembic commands ###
