"""initial vocabulary tables

Revision ID: 6b3efc08b610
Revises: 
Create Date: 2026-07-19 17:56:12.972936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b3efc08b610'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('skritter_vocab_id', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('writing', sa.Text(), nullable=False),
    sa.Column('reading', sa.Text(), nullable=True),
    sa.Column('definition_en', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skritter_vocab_id')
    )
    op.create_table('vocabulary_lists',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('skritter_list_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skritter_list_id')
    )
    op.create_table('list_vocabulary',
    sa.Column('list_id', sa.BigInteger(), nullable=False),
    sa.Column('vocabulary_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['vocabulary_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('list_id', 'vocabulary_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_vocabulary')
    op.drop_table('vocabulary_lists')
    op.drop_table('vocabulary_items')
    # ### end Alembic commands ###
