"""add generation request and raw payload tables

Revision ID: 73e4edaa4c08
Revises: f94bff3e8def
Create Date: 2026-08-01 13:50:00.656380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73e4edaa4c08'
down_revision: Union[str, Sequence[str], None] = 'f94bff3e8def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_generation_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vocabulary_list_id', sa.BigInteger(), nullable=False),
    sa.Column('target_hsk_level', sa.SmallInteger(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('target_word_count', sa.SmallInteger(), nullable=False),
    sa.Column('target_vocabulary_count', sa.SmallInteger(), nullable=False),
    sa.Column('selected_vocabulary_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('model_parameters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('validation_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider_request_id', sa.Text(), nullable=True),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status = ANY (ARRAY['queued'::text, 'running'::text, 'succeeded'::text, 'failed'::text])", name='story_generation_requests_status_check'),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= started_at', name='story_generation_requests_completed_after_started_check'),
    sa.CheckConstraint('target_hsk_level BETWEEN 1 AND 6', name='story_generation_requests_hsk_level_check'),
    sa.CheckConstraint('target_vocabulary_count BETWEEN 1 AND 15', name='story_generation_requests_vocabulary_count_check'),
    sa.CheckConstraint('target_word_count > 0', name='story_generation_requests_word_count_check'),
    sa.ForeignKeyConstraint(['vocabulary_list_id'], ['vocabulary_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_generation_payloads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('generation_request_id', sa.BigInteger(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generation_request_id'], ['story_generation_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('stories', sa.Column('generation_request_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(
        'stories_generation_request_id_key', 'stories', ['generation_request_id']
    )
    op.create_foreign_key(
        'stories_generation_request_id_fkey',
        'stories',
        'story_generation_requests',
        ['generation_request_id'],
        ['id'],
    )
    op.add_column('story_vocabulary_items', sa.Column('requested', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('story_vocabulary_items', sa.Column('used', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('story_vocabulary_items', 'used')
    op.drop_column('story_vocabulary_items', 'requested')
    op.drop_constraint('stories_generation_request_id_fkey', 'stories', type_='foreignkey')
    op.drop_constraint('stories_generation_request_id_key', 'stories', type_='unique')
    op.drop_column('stories', 'generation_request_id')
    op.drop_table('raw_generation_payloads')
    op.drop_table('story_generation_requests')