"""add question flags

Revision ID: 7589b9edbfac
Revises: 3fd92743c323
Create Date: 2026-09-26 07:41:51.904877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7589b9edbfac'
down_revision: Union[str, Sequence[str], None] = '3fd92743c323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Additive (a new table), so older code runs on this schema after a
    rollback; it just ignores the table and offers no flag button.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_flags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('story_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('question_index >= 0', name='question_flags_question_index_check'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('question_flags_story_id_idx', 'question_flags', ['story_id'], unique=False)
    op.create_index('question_flags_user_id_idx', 'question_flags', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('question_flags_user_id_idx', table_name='question_flags')
    op.drop_index('question_flags_story_id_idx', table_name='question_flags')
    op.drop_table('question_flags')
    # ### end Alembic commands ###
