"""add auth events

Revision ID: e88431d6976e
Revises: 7589b9edbfac
Create Date: 2026-09-26 11:45:25.409682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88431d6976e'
down_revision: Union[str, Sequence[str], None] = '7589b9edbfac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Additive (a new table), so older code runs on this schema after a
    rollback; it just stops recording logins and logouts.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('client_ip', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.CheckConstraint("event_type <> 'login_unknown_user' OR user_id IS NULL", name='auth_events_unknown_user_has_no_user_check'),
    sa.CheckConstraint("event_type = ANY (ARRAY['login_succeeded'::text, 'login_wrong_password'::text, 'login_unknown_user'::text, 'logout'::text])", name='auth_events_event_type_check'),
    sa.CheckConstraint("event_type IN ('login_succeeded', 'logout') OR session_id IS NULL", name='auth_events_session_id_check'),
    sa.ForeignKeyConstraint(['session_id'], ['auth_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('auth_events_occurred_at_idx', 'auth_events', ['occurred_at'], unique=False)
    op.create_index('auth_events_session_id_idx', 'auth_events', ['session_id'], unique=False)
    op.create_index('auth_events_user_id_idx', 'auth_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('auth_events_user_id_idx', table_name='auth_events')
    op.drop_index('auth_events_session_id_idx', table_name='auth_events')
    op.drop_index('auth_events_occurred_at_idx', table_name='auth_events')
    op.drop_table('auth_events')
    # ### end Alembic commands ###
