"""add target_hsk and updated_at to stories

Revision ID: f94bff3e8def
Revises: 5790430a6366
Create Date: 2026-08-01 12:58:27.525396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94bff3e8def'
down_revision: Union[str, Sequence[str], None] = '5790430a6366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('target_hsk', sa.Integer(), nullable=True))
    op.add_column('stories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'updated_at')
    op.drop_column('stories', 'target_hsk')
    # ### end Alembic commands ###
